# Generated by Django 4.1.1 on 2022-09-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_aluno_cpt_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='cpt',
            new_name='cpf',
        ),
    ]
