# Generated by Django 4.2.1 on 2023-05-27 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0003_rename_cpt_aluno_cpf"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("B", "Básico"),
                            ("I", "Intermediário"),
                            ("A", "Avançado"),
                        ],
                        default="B",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("M", "Matutino"),
                            ("V", "Vespertino"),
                            ("N", "Noturno"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="escola.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("rg", models.CharField(max_length=9)),
                ("cpf", models.CharField(max_length=11)),
                ("birth_date", models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name="matricula",
            name="aluno",
        ),
        migrations.RemoveField(
            model_name="matricula",
            name="curso",
        ),
        migrations.DeleteModel(
            name="Aluno",
        ),
        migrations.DeleteModel(
            name="Curso",
        ),
        migrations.DeleteModel(
            name="Matricula",
        ),
        migrations.AddField(
            model_name="registration",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="escola.student"
            ),
        ),
    ]
